### PR TITLE
Count lines in comments and double quoted strings

### PR DESCRIPTION
**Pull request by paran1**

### CODE REVIEW

**Comment by paran1** [comment]
This fixes #565. Was mostly fixed by the recent pull request #570, however that only fixed single quoted strings. This trivial commit uses the same fix for double quoted strings.

**Comment by rnelson0** [comment]
@paran1 Thanks for catching this. Can you add a test for double quoted strings with newlines, so that we make sure there are no future regressions?

**Comment by paran1** [comment]
Like this? Please double check this as Ruby isn't the language I am most familiar with.

I also added a fix so lines are counted correctly in the special case where the multi line strings end with newline. I ran into that while writing the test, and it was due to rather peculiar behaviour of Rubys split().

Also, the last commit might not be strictly necessary, I can remove it again if you don't like it.

**Comment by paran1** [comment]
Rebased and modified to also handle comments, which was mentioned in #403.

**Comment by rnelson0** [comment]
@paran1 looks good to me. Did you try this with the test manifest from #403?

**Comment by paran1** [comment]
I just tried the test from #403 and that also works as expected now.

I have tested with test manifests containing all three types of multi-line strings, my examples from #565 and of course the places in our real manifests where we hit this.

**Comment by rnelson0** [comment]
Awesome! The unit tests seemed to account for it, but I definitely like to test in the real world too. I'll go ahead and merge this then.

**Pull request merged**
