### PR TITLE
Add fix to "ensure found on line but it's not the first attribute"

### PR DESCRIPTION
**Pull request by sathieu**

### CODE REVIEW

**Comment by raphink** [comment]
Wouldn't it be easier to use `tokens#insert` to insert the ensure tokens in the proper position and then delete them from their current position?

**Comment by rnelson0** [comment]
This will require spec tests to move forward. Are you still interested in pursuing this @sathieu?

**Comment by rnelson0** [comment]
@sathieu Bump, still interested?

**Comment by hlindberg** [comment]
The rule "double quoting without variable" is odd - you may want a double quoted strings for other reasons than interpolation, such as using the richer set of escapes available in double quoted strings, or when you need to include single quotes in the string.

**Comment by sathieu** [comment]
Build now passing with spec (also I updated the description which was incorrect)

**Comment by rnelson0** [comment]
@sathieu This looks awesome! I'm going to put out the bat call to get someone else to review it, but it looks great to me.

**Comment by ghoneycutt** [comment]
+1 I did some simple tests and it is working as expected.

**Comment by rnelson0** [comment]
Thanks everyone, merging now!

**Pull request merged**
