### PR TITLE
Let command line args override config from files

### LINKED ISSUE #879: Command line options do not override options from config files
The [documentation for configuration files](https://github.com/rodjek/puppet-lint/#configuration-file) currently states:

> Flags specified on the command line take final precedence and override all config file options.

IMHO that behaviour makes sense and I guess most users will expect that behaviour.

Unfortunately the opposite seems to be true: Options from config files will override options given on the command line:

```
$ git clone https://github.com/rodjek/puppet-lint.git
$ cd puppet-lint
$ echo '$foo = 42' > test.pp
$ echo '--only-checks=80chars' > .puppet-lint.rc
$ sed -i '/enabled_checks.each/a\
      pp check' lib/puppet-lint/checks.rb   ## debug output: all enabled checks
$ ./bin/puppet-lint --only-checks=140chars test.pp   ## config file has precedence over command line arg
:"80chars"
$ > .puppet-lint.rc
$ ./bin/puppet-lint --only-checks=140chars test.pp   ## it works with empty config file
:"140chars"
```

### PR DESCRIPTION
**Pull request by usev6**
Arguments given on the command line should override those from
config files. That implies that config files must be read first.
Only peeking into the command line args can show if config files
should be used at all.

This change might break existing setups.

Fixes #879.

### CODE REVIEW

**Comment by rodjek** [comment]
Thanks @usev6, can you add a test to `spec/puppet-lint/bin_spec.rb` for this behaviour?

**Comment by usev6** [comment]
Yes, adding a test for this behaviour makes a lot of sense. I'll try to come up with something later today.

**Comment by usev6** [comment]
I have to admit, that I don't have much experience with rspec. But I think the test I added should work. I thought about doing the whole test in a temporary directory, because that would allow to create a ```.puppet-lint.rc``` file unconditionally. Or would there even be a way to mock the reading of options from ```~/.puppet-lint.rc```?

**Comment by rodjek** [comment]
Thanks for that @usev6, I refactored the test a bit to run the test inside a temporary directory (removing the need for the `.puppet-lint.rc` existence check)

**Comment by usev6** [comment]
@rodjek thanks for cleaning up the test. And while I'm at it: Thanks for puppet-lint. Also the tutorial at http://puppet-lint.com/developer/tutorial/ was very helpful and made writing [two](https://github.com/usev6/puppet-lint-cuddled_else-check) small [plugins](https://github.com/usev6/puppet-lint-uncuddled_else-check/commits/master) very easy -- though I never wrote a gem before.

**Pull request merged**
