### PR TITLE
Improve Rake task

### PR DESCRIPTION
**Pull request by raphink**
When using the Rake task with an open glob such as `**/*`, `puppet-lint` will fail to load directories.

### CODE REVIEW

**Comment by raphink** [comment]
Hey @rodjek , are you interested in this pr?

**Comment by raphink** [comment]
Thanks for merging!

**Comment by rodjek** [comment]
@raphink Sorry it took so long, took a bit of a break from open source :)

**Comment by raphink** [comment]
I can totally understand, no need to apologize!

**Pull request merged**
