### PR TITLE
Adding support for logging to STDOUT as JSON

### PR DESCRIPTION
**Pull request by binford2k**
supersedes #421 by adding a more robust json validating spec test

@kylog can you review the commit I added?

### CODE REVIEW

**Comment by binford2k** [comment]
Hrm. It looks like the `rspec-json_expectations` gem won't parse on Ruby 1.8. As that shouldn't affect end functionality at all, how do you suggest I proceed with this? I could make the load conditional and fall back to the old regex for 1.8

**Comment by kylog** [comment]
Wow, I hadn't noticed that travis was running against 1.8.7 (which has been EOL for almost 2 years). I'm tempted to drop support for ruby < 2.1 (which is on maintenance-only itself). That probably means another major, but we could roll this feature in then (and avoid the 1.8 workarounds completely).

Thoughts @binford2k or @rnelson0?

**Comment by rnelson0** [comment]
Ugh, Ruby versions. I'll open an issue to track that separately. I like the approach here, though, and think we should proceed, as deprecating ruby 1.8.7 will involve more than just the code here.

**Comment by rnelson0** [comment]
@binford2k since we've decided to keep 1.8.7 for now, I think we are okay to proceed, if you can rebase your PR.

**Comment by rnelson0** [comment]
@binford2k This will need a rebase, and may cause a rebase for #589 if this is accepted first.

**Comment by binford2k** [comment]
Output example

```
manifests $ RUBYLIB=~/Projects/puppet-lint/lib ~/Projects/puppet-lint/bin/puppet-lint fail.pp --json
[
  {
    "message": "test::foo not in autoload module layout",
    "line": 2,
    "column": 7,
    "kind": "error",
    "check": "autoloader_layout",
    "fullpath": "/Users/ben/Projects/puppet-lint/spec/fixtures/test/manifests/fail.pp",
    "path": "fail.pp",
    "filename": "fail.pp",
    "KIND": "ERROR"
  }
]
```

**Pull request merged**
