### PR TITLE
True up reserved keywords

### PR DESCRIPTION
**Pull request by rnelson0**
Link to reference point inside puppet code where reserved words are maintained.
  Ordered keywords to match order in puppet, for easier comparison.
  Add tokens for Application Management, to be integrated later.

### CODE REVIEW

**Comment by garrettrowell** [comment]
regarding the APP_MANAGEMENT_TOKENS
https://github.com/puppetlabs/puppet/blob/master/lib/puppet/pops/parser/lexer2.rb#L146-L159
Puppet[:app_management] is set to 'false' by default. When this is the case they are not reserved. However when Puppet[:app_management] is true they are reserved

**Comment by rnelson0** [comment]
@rkhatibi I'm going to ask @hel to rule on that one.

@garrettrowell We will have to make sure we support them via toggle, this is just to add them regardless (the `true` value is misleading since it's just there to get the keys into the hash).

**Comment by hel** [comment]
I think you mentioned the wrong person.

**Comment by rnelson0** [comment]
@rkhatibi I'm going to ask @hlindberg to rule on the reserved word list.

**Comment by hlindberg** [comment]
keyword list looks ok now

**Comment by rnelson0** [comment]
@rkhatibi I tested and the reserved words on that page are limited in where they can be placed, not in their usage as parameter names.

Puppet-lint isn't actually using the keywords hash, but making it available for plugins like [this](https://github.com/buty4649/puppet-lint-pepabo-style/blob/c9eba21afdc1539155223309eb1c5efd8abd4ebb/lib/puppet-lint/plugins/check_pepabo_style.rb#L23) so they do not have to maintain a list themselves. I was pretty certain there is an existing plugin that uses this but I cannot find it.

**Pull request merged**
