### PR TITLE
Show logs in rspec tests

### PR DESCRIPTION
**Pull request by ghoneycutt**

### CODE REVIEW

**Comment by rnelson0** [comment]
I am okay with this, I know @binford2k has some thoughts on it, though.

**Comment by binford2k** [comment]
I greatly GREATLY prefer the "no news is good news" mode, because with `--format documentation` problems get lost in the noise--especially on longer running test suites. With the default, you can see at a glance how your tests are proceeding.

That said, this test isn't terribly long and the failure summary is displayed at the end either way. What's the intent for having super verbose output?

**Comment by ghoneycutt** [comment]
There do not seem to be any costs to having more information available, so I would prefer to have more.

**Comment by rnelson0** [comment]
Sounds good, we can always change it later!

**Pull request merged**
