### PR TITLE
Add future parser's Puppet Types token type

### PR DESCRIPTION
**Pull request by mcanevet**

### CODE REVIEW

**Comment by raphink** [comment]
:+1: , definitely needed

**Comment by strider** [comment]
:+1:

**Comment by jlambert121** [comment]
Absolutely needed

**Comment by bastelfreak** [comment]
Hi @rodjek, could you please have a look here?

**Comment by ahpook** [comment]
Merging, thanks for the 👍 s - for future reference that `|` separated list of types seems kind of brittle, any thoughts on how to refactor that?

**Comment by hlindberg** [comment]
The list of types is both brittle, and not correct since data types can be namespaced. The Rule for data types is actually the same as for a CLASSREF, this because all references to things like File, User, etc. are also data types, and so are the references to user defined resource types (created with 'define').
Not sure what puppet-lint does with the CLASSREF that would make it unsuitable for all data types. The problem here is that it is impossible to statically know what a CLASSREF is referring to as that requires loading the actual referenced entity (a resource type in ruby, a data type, type alias, or a user defined resource type).
The static list in this PR is already behind, and there will be additional types added.

**Pull request merged**
