### PR TITLE
Add parameter documentation check

### PR DESCRIPTION
**Pull request by michaeltchapman**
This patch adds a new check to ensure that parameters
to classes are documented. It will ensure there is a
block of the form:
```
[*<parameter_name>*]
(<Optional | Required>) <description>
```
and if optional will check for:
```
Defaults to <default value>
```

### CODE REVIEW

**Comment by rnelson0** [comment]
This is a good check to have, but is not required by the style guide. See #484 to discuss a method to add new checks that are disabled by default, if you would like to assist.

This will need tests, as well.

**Comment by hlindberg** [comment]
The style of documentation this test asserts is not the recommended yard style processed by Puppet Strings. Thus this assertion is counter productive.

**Comment by rnelson0** [comment]
@hlindberg do you have a link to that recommended style?

**Comment by hlindberg** [comment]
https://github.com/puppetlabs/puppetlabs-strings/blob/master/README.md

Also note that when Puppet Strings is generating documentation it picks up the names and data types automatically - and compares those to what a user has written to ensure docs are up to date (+ much more).

**Comment by ghoneycutt** [comment]
@michaeltchapman You can also release individual checks as their own gems, which allows you to enforce style that is not covered by the official style guide.

Here's a few examples

https://github.com/voxpupuli/puppet-lint-reference_on_declaration_outside_of_class-check
https://github.com/voxpupuli/puppet-lint-file_ensure-check

**Pull request closed without merging**
