### PR TITLE
Add various helper functions

### PR DESCRIPTION
**Pull request by raphink**
## function_indexes

    Returns an Array of Hashes with the positions of all the function calls
    within the tokenised manifest. Each Hash has the following Symbol keys:
  
    * :start -   The Integer position in the `tokens` Array pointing to the
                 first token of the function call.
    * :end -     The Integer position in the `tokens` Array pointing to the
                 last token of the function call.
    * :tokens -  A subset of the `tokens` Array, from the :start to :end
                 positions.

## array_indexes

    Returns an Array of Hashes with the positions of all the array values
    within the tokenised manifest. Each Hash has the following Symbol:
    
    * :start -   The Integer position in the `tokens` Array pointing to
                 the first token of the array value.
    * :end -     The Integer position in the `tokens` Array pointing to
                 the last token of the array value.
    * :tokens -  A subset of the `tokens` Array, from the :start to :end
                 positions.

## hash_indexes

    Add a hash_indexes method
    
    Returns an Array of Hashes with the positions of all the hash values
     within the tokenised manifest. Each Hash has the following Symbol:
    
    * :start -   The Integer position in the `tokens` Array pointing to
                 the first token of the hash value.
    * :end -     The Integer position in the `tokens` Array pointing to
                 the last token of the hash value.
    * :tokens -  A subset of the `tokens` Array, from the :start to :end
                 positions.

## defaults_indexes

    Returns an Array of Hashes with the positions of all the defaults declarations
     within the tokenised manifest. Each Hash has the following Symbol:
    
    * :start -   The Integer position in the `tokens` Array pointing to
                 the first token of the defaults declaration.
    * :end -     The Integer position in the `tokens` Array pointing to
                 the last token of the defaults declaration.
    * :tokens -  A subset of the `tokens` Array, from the :start to :end
                 positions.

### CODE REVIEW

**Comment by raphink** [comment]
@rodjek Are you interested in merging these methods?

**Comment by mcanevet** [comment]
@rodjek is there a way to file a PR against the online doc for these additions?

**Comment by rodjek** [comment]
@mcanevet Yep, just base your changes on the `gh-pages` branch and create a PR

**Comment by raphink** [comment]
Thanks for the reply @rodjek. While you're around, could you take a look at https://github.com/rodjek/rspec-puppet/pull/261 and comment please?

**Pull request merged**
