### PR TITLE
Add better description of the problem in arrow_alignment check

### PR DESCRIPTION
**Pull request by rnelson0**
Related to #424. @TomOnTime looking for your feedback to see if this is what you'd like to see.

### CODE REVIEW

**Comment by rnelson0** [comment]
Example of old and new output:
```
[rnelson0@build03 puppet-lint:master±]$ be puppet-lint foo.pp
ERROR: example not in autoload module layout on line 2
WARNING: indentation of => is not properly aligned on line 9

[rnelson0@build03 puppet-lint:arrowalignmessage±]$ be puppet-lint foo.pp
ERROR: example not in autoload module layout on line 2
WARNING: indentation of => is not properly aligned (expected in column 39, but found it in column 35) on line 9
```

**Comment by rnelson0** [comment]
This is going to break tests which are looking for static error messages, but I'm not going to fix those until we know what this should look like.

**Comment by TomOnTime** [comment]
Yes, I think that warning message would make it a lot more clear what is to be fixed.

**Comment by rnelson0** [comment]
@binford2k Thoughts before I touch up the spec tests?

**Comment by rnelson0** [comment]
@binford2k Rspec tests are touched up. I'm not sure that's the best way to do this but it's working; I can tweak it if you have a better way to match it.

**Pull request merged**
