### PR TITLE
(maint) Fixes puppet-lint json formatting to output valid json to stdout

### PR DESCRIPTION
**Pull request by bmjen**

### CODE REVIEW

**Comment by ghoneycutt** [comment]
I was not able to reproduce the issue. Ran `puppet-lint path/to/manifest.pp --json > test.json; jq . test.json` with no issues.

**Comment by bmjen** [comment]
@ghoneycutt Try running the command with more than 1 target, the result will be: 

```
[
{
"message": "apache not in autoload module layout",
"line": 15,
"column": 7,
"kind": "error",
"check": "autoloader_layout",
"fullpath": "/Users/bmjen/proj/modules/puppetlabs-apache/manifests/init.pp",
"path": "manifests/init.pp",
"filename": "init.pp",
"KIND": "ERROR"
},
{
"message": "line has more than 140 characters",
"line": 111,
"column": 140,
"kind": "warning",
"check": "140chars",
"fullpath": "/Users/bmjen/proj/modules/puppetlabs-apache/manifests/init.pp",
"path": "manifests/init.pp",
"filename": "init.pp",
"KIND": "WARNING"
}
]
[
{
"message": "apache::mod not in autoload module layout",
"line": 1,
"column": 8,
"kind": "error",
"check": "autoloader_layout",
"fullpath": "/Users/bmjen/proj/modules/puppetlabs-apache/manifests/mod.pp",
"path": "manifests/mod.pp",
"filename": "mod.pp",
"KIND": "ERROR"
},
{
"message": "defined type not documented",
"line": 1,
"column": 1,
"kind": "warning",
"check": "documentation",
"fullpath": "/Users/bmjen/proj/modules/puppetlabs-apache/manifests/mod.pp",
"path": "manifests/mod.pp",
"filename": "mod.pp",
"KIND": "WARNING"
}
]
```

**Comment by bmjen** [comment]
I'll fix tests. Mainly just wanted to get this PR up for now.

**Comment by ghoneycutt** [comment]
jq was able to parse it, but I did expect a comma at

```
]
[
``

**Comment by ghoneycutt** [comment]
This should have a couple functional tests where it would run against one file and against multiple files and check that the json created is valid.

**Comment by bmjen** [comment]
@ghoneycutt right, the missing comma causes a parse error in ruby's JSON.parse and various other JSON parsers.

**Comment by bmjen** [comment]
@ghoneycutt I'll add those shortly. 👍

**Comment by bmjen** [comment]
@ghoneycutt @rodjek additional test was added to test json output of multiple targets with offenses. I've validated that this test fails on the old code with a JSON.parse error and passes on the new code.

**Pull request merged**
