### PR TITLE
Ignore selectors when finding resource type

### LINKED ISSUE #663: Missed bad file modes in file with multiple resource bodies
In a file resource with multiple resource body, both file_mode and unquoted_file_mode miss subsequent bad file modes if there is a selector in one of the resource bodies.

Tested using puppet-lint 2.1.1 and current master (e90c1f4bf73823155268ab893708b371a723f85c)

(The examples below violate the style guide by not having a default body. That was removed to create more minimal test cases.)

### Working example
Both `file_mode` and `unquoted_file_mode` warns about three files as expected.
```puppet
# multi_body_file_bad_modes.pp
file {
  '/tmp/foo1':
    mode => 644;
  '/tmp/foo2':
    mode => 644;
  '/tmp/foo3':
    mode => 644;
}
```
```
$ puppet-lint multi_body_file_bad_modes.pp
WARNING: unquoted file mode on line 4
WARNING: unquoted file mode on line 6
WARNING: unquoted file mode on line 8
WARNING: mode should be represented as a 4 digit octal value or symbolic mode on line 4
WARNING: mode should be represented as a 4 digit octal value or symbolic mode on line 6
WARNING: mode should be represented as a 4 digit octal value or symbolic mode on line 8
```

### Bug example 1
Same code, with a selector added in the first file resource body.
`selector_inside_resource` correctly warns about the selector.
But both file mode checks now only warns about the first file.

```puppet
# multi_body_file_bad_modes_selector.pp
file {
  '/tmp/foo1':
    ensure => $foo ? { default => absent },
    mode   => 644;
  '/tmp/foo2':
    mode => 644;
  '/tmp/foo3':
    mode => 644;
}
```
```
$ puppet-lint multi_body_file_bad_modes_selector.pp
WARNING: selector inside resource block on line 4
WARNING: unquoted file mode on line 5
WARNING: mode should be represented as a 4 digit octal value or symbolic mode on line 5
```
### Bug example 2
Same code, with the first file mode fixed.
The later file modes are still ignored, so this example gives no file mode warnings.
```puppet
# multi_body_file_bad_modes_selector_first_ok.pp
file {
  '/tmp/foo1':
    ensure => $foo ? { default => absent },
    mode   => '0644';
  '/tmp/foo2':
    mode => 644;
  '/tmp/foo3':
    mode => 644;
}
```
```
$ puppet-lint multi_body_file_bad_modes_selector_first_ok.pp
WARNING: selector inside resource block on line 4
```

### PR DESCRIPTION
**Pull request by paran1**
Fixes #663

### CODE REVIEW

**Comment by rnelson0** [comment]
Do we have a good test case or two for this, to ensure no regressions in the future?

**Comment by paran1** [comment]
@rothsa have made test cases using the examples from #663. I'll merge that into my branch so it gets included in the pull request. However it is getting to late for me, so that will have to wait until tomorrow.

**Comment by rodjek** [comment]
@paran1 @rothsa :+1: I'll review this once the tests are included

**Comment by rodjek** [comment]
I've merged the tests with this fix into a new PR (because I want this fix in the 2.2.0 release and we're running out of time for that) that now supersedes this PR, so I'm closing this in favour of #678.

**Comment by paran1** [comment]
Glad that you took care of it!
Sorry I failed to update this last week as I said.

**Pull request closed without merging**
